version: 2
project_name: gsi

env_files:
  github_token: ~/.config/goreleaser/github_token

before:
  hooks:
    - go mod download

builds:
  - id: gsi-linux
    binary: gsi
    env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: gsi-macos
    binary: gsi
    env: [CGO_ENABLED=0]
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

  - id: gsi-windows
    binary: gsi
    env: [CGO_ENABLED=0]
    goos: [windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    mod_timestamp: "{{ .CommitTimestamp }}"

universal_binaries:
  - id: gsi-macos
    replace: true
    hooks:
      post: uv run /Users/joescharf/.local/bin/pycodesign.py gsi_pycodesign.ini -O {{ .Version }}

archives:
  - id: gsi-linux-archive
    ids: [gsi-linux]
    formats: ["tar.gz"]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    files: [README.md]

  - id: gsi-macos-archive
    ids: [gsi-macos]
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else if eq .Arch \"all\" }}universal{{ else }}{{ .Arch }}{{ end }}"
    files: [README.md]

  - id: gsi-windows-archive
    ids: [gsi-windows]
    formats: ["zip"]
    name_template: "{{ .ProjectName }}_{{ title .Os }}_{{ if eq .Arch \"amd64\" }}x86_64{{ else }}{{ .Arch }}{{ end }}"
    files: [README.md]

signs:
  - id: notarize-macos-zip
    cmd: sh
    args:
      - -c
      - 'xcrun notarytool submit "${artifact}" --keychain-profile SCHARFNADO_LLC --wait && touch "${signature}"'
    artifacts: archive
    ids:
      - gsi-macos-archive
    signature: "${artifact}.notarized"
    output: true

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: joescharf
    name: gsi
  ids: [gsi-macos-archive, gsi-linux-archive, gsi-windows-archive]
  extra_files:
    - glob: ./dist/gsi_macos_universal.pkg
  draft: false
  prerelease: auto

# brew install joescharf/tap/gsi
homebrew_casks:
  - name: gsi
    ids:
      - gsi-macos-archive
    repository:
      owner: joescharf
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Casks
    skip_upload: auto
    homepage: "https://github.com/joescharf/gsi"
    description: "Initialize Go projects with best practices and tooling"

dockers_v2:
  - images:
      - "ghcr.io/joescharf/gsi"
    tags:
      - "v{{ .Version }}"
      - latest
