# goreleaser release --clean --verbose
# goreleaser release --snapshot --clean --skip homebrew,docker

project_name: gsi
version: 2

before:
  hooks:
    - go mod download

builds:
  - id: gsi
    binary: gsi
    dir: .
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/joescharf/gsi/cmd.version={{.Version}}
      - -X github.com/joescharf/gsi/cmd.commit={{.Commit}}
      - -X github.com/joescharf/gsi/cmd.date={{.Date}}

  - id: gsi-macos
    binary: gsi
    dir: .
    main: main.go
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
    ldflags:
      - -X github.com/joescharf/gsi/cmd.version={{.Version}}
      - -X github.com/joescharf/gsi/cmd.commit={{.Commit}}
      - -X github.com/joescharf/gsi/cmd.date={{.Date}}

# MacOS Universal Binaries
universal_binaries:
  - id: gsi-macos
    replace: true

archives:
  - id: gsi-linux-archive
    ids:
      - gsi

  - id: gsi-archive
    ids:
      - gsi-macos
    formats:
      - zip
    files:
      - none*

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: joescharf
    name: gsi
  ids:
    - gsi-archive
    - gsi-linux-archive
  draft: false

snapshot:
  version_template: "{{ incpatch .Version }}-devel"

# brew install joescharf/tap/gsi
brews:
  - repository:
      owner: joescharf
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/joescharf/gsi"
    description: "Initialize Go projects with best practices and tooling"
    install: |
      bin.install "gsi"
    test: |
      system "#{bin}/gsi", "version"

changelog:
  sort: asc
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs:"
      - "^test:"

# Multi-platform Docker images
dockers_v2:
  - images:
      - "ghcr.io/joescharf/gsi"
    tags:
      - "v{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.title": "{{ .ProjectName }}"
      "org.opencontainers.image.description": "{{ .ProjectName }}"
      "org.opencontainers.image.url": "https://github.com/joescharf/{{ .ProjectName }}"
      "org.opencontainers.image.source": "https://github.com/joescharf/{{ .ProjectName }}"
      "org.opencontainers.image.version": "{{ .Version }}"
      "org.opencontainers.image.revision": "{{ .FullCommit }}"
